# Generated by Django 5.2.6 on 2025-09-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userlogininformations_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogininformations',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
