# Generated by Django 5.2.6 on 2025-09-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userlogininformations_last_login_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlogininformations',
            options={'verbose_name': 'User Login Information', 'verbose_name_plural': 'User Login Informations'},
        ),
        migrations.AlterField(
            model_name='userlogininformations',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
